### ISSUE TITLE
Wired syntax in Makefile

### ISSUE THREAD

**Issue by Naetw** [sysprog21/linux-list#3]
https://github.com/sysprog21/linux-list/blob/e2bcbc4e633cfa19ff2de449fce30b10319603eb/Makefile#L42

After reading the GNU make manual and the history (git log) of Makefile, I think the second colon is a typo and it should be an equal sign? Like this:

```make
deps := $(TESTS:%=%.o.d) 
```

Which is equivalent to:

```make
$(patsubst %,%.o.d,$(TESTS))
```

And if this is the expected behavior, we can just use `$(deps)` in target clean instead of `$(TESTS:=.o.d)`.

https://github.com/sysprog21/linux-list/blob/e2bcbc4e633cfa19ff2de449fce30b10319603eb/Makefile#L65

**Comment by jserv** [comment]
It was copy-n-paste mistake. Please send pull request to fix.

**Comment by Naetw** [comment]
Done. Please check #4.
