### ISSUE TITLE
Removed copyright header

### ISSUE THREAD

**Issue by ecsv** [sysprog21/linux-list#8]
Hi, I've just noticed that this repository contains mostly code copied from my repository https://github.com/ecsv/linux-like-list/ - but your repository has the the copyright headers removed. Instead the copyright is shown as "Copyright (C) 2018 National Cheng Kung University, Taiwan." in the LICENSE file.

Please readd my copyright + license information again for all the code portions which were copied.

**Comment by jserv** [comment]
It was my fault of copying copyright template. Now, it is fixed. Thank @ecsv for the great work.
